DROP TABLE Items;

CREATE TABLE Items (
  itemId SERIAL PRIMARY KEY,
  name VARCHAR,
  price DECIMAL,
  category VARCHAR,
  ingredients VARCHAR,
  startDate TIMESTAMP,
  endDate TIMESTAMP,
  picture VARCHAR(2048),
  itemDesc VARCHAR(2048) 
);

INSERT INTO Items (name, price, category, ingredients, startDate, endDate, picture, itemDesc) VALUES
    ('Bacon Cheeseburger', 8.29, 'Burger', 'bacon,cheese,buns,beef patties,lettuce,tomatoes,pickles,onions',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://clipart-library.com/images_k/transparent-cheeseburger/transparent-cheeseburger-12.png', 'A mouthwatering combination of a juicy beef patty topped with crispy bacon strips, melted cheese, fresh lettuce, ripe tomato slices, and tangy pickles, served on a toasted bun.'),
    ('Black Bean Burger', 7.59, 'Burger', 'black bean patties,buns,lettuce,tomatoes,pickles,onions',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.seekpng.com/png/full/233-2333816_black-bean-burger-wendys-black-bean-burger.png', 'A vegetarian delight featuring a savory black bean patty seasoned with herbs and spices, served on a toasted whole wheat bun with lettuce, tomato, onion, and a side of chipotle mayo.'),
    ('Cheeseburger', 6.89, 'Burger', 'cheese,buns,beef patties,lettuce,tomatoes,pickles,onions',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://clipart-library.com/images_k/transparent-cheeseburger/transparent-cheeseburger-13.png', 'A classic favorite, featuring a succulent beef patty topped with gooey melted cheese, fresh lettuce, tomato, onion, and pickles, served on a soft, toasted bun.'),
    ('Gig ''em Patty Melt', 7.59, 'Burger', 'texas toast,american cheese,Gig-em sauce,grilled chicken',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://static.freddysusa.com/wp-content/uploads/2016/01/Hero_Burger_DoublePattyMelt_1011.png', 'A hearty Aggie twist on the classic patty melt, featuring a juicy beef patty, caramelized onions, and melted Swiss cheese.'),
    ('Classic Hamburger', 6.89, 'Burger', 'buns,beef patties,lettuce,tomatoes,pickles,onions',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://pngimg.com/uploads/burger_sandwich/burger_sandwich_PNG4160.png', 'A simple yet satisfying choice, featuring a juicy beef patty served on a toasted bun with fresh lettuce, tomato, onion, pickles, and condiments.'),
    ('Aggie Chicken Club', 8.39, 'Chicken', 'buns,grilled chicken,bacon,lettuce,tomatoes,Swiss cheese,Gig-em sauce',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://i.pinimg.com/originals/df/2b/6f/df2b6f31d8346e2e35c366dbe773db54.png', 'A flavorful sandwich featuring grilled chicken breast, crispy bacon, melted Swiss cheese, fresh lettuce, ripe tomato slices, and creamy avocado, served on toasted whole wheat bread.'),
    ('Rev''s Grilled Chicken Sandwich', 8.39, 'Chicken', 'buns,grilled chicken,lettuce,tomatoes,pickles,onions,spicy ranch sauce',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://mytaleswithtwo.com/wp-content/uploads/2014/05/ChickfilA-Grilled-Chicken-Sandwich.png', 'A delicious option featuring tender grilled chicken breast topped with melted cheddar cheese, crisp lettuce, ripe tomato slices, and zesty barbecue sauce.'),
    ('Spicy Chicken Sandwich', 8.39, 'Chicken', 'buns,crispy chicken tenders,lettuce,tomatoes,pickles,onions,spicy ranch sauce',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://toppng.com/public/uploads/thumbnail/spicy-crispy-chicken-sandwich-11549663243dlgmffyr1b.png', 'A fiery delight featuring a crispy breaded chicken breast seasoned with spicy spices, served on a soft bun with cool lettuce, tomato, and creamy mayo.'),
    ('Chicken Caesar Salad', 8.29, 'Salad', 'lettuce,grilled chicken,parmesan cheese,croutons,caesar dressing',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.nicepng.com/png/detail/320-3201511_object-moved-chicken-caesar-salad-png.png', 'A classic salad featuring crisp romaine lettuce tossed with grilled chicken breast, crunchy croutons, shredded Parmesan cheese, and tangy Caesar dressing.'),
    ('Double Scoop Ice Cream', 3.29, 'Dessert', 'ice cream',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://clipart-library.com/images_k/ice-cream-png-transparent/ice-cream-png-transparent-9.png',  'Indulge in a double dose of creamy, flavorful ice cream, served in a dish or cone with your choice of toppings.'),
    ('Aggie Shakes', 4.49, 'Dessert', 'ice cream,milk,whipped cream,chocolate syrup',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.seekpng.com/png/full/243-2438791_strawberry-hand-spun-shake-health-shake.png', 'Cool off with a refreshing milkshake available in various flavors, blended to perfection and topped with whipped cream.'),
    ('Cookie Ice Cream Sundae', 4.69, 'Dessert', 'ice cream,cookies,whipped cream,chocolate syrup',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.pngall.com/wp-content/uploads/13/Sundae-PNG-Pic.png', 'A delightful dessert featuring scoops of creamy ice cream nestled atop a warm, gooey chocolate chip cookie, drizzled with chocolate syrup and crowned with whipped cream and a cherry.'),
    ('Root Beer Float', 5.49, 'Beverage', 'root beer,ice cream',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.pikpng.com/pngl/b/265-2652828_root-beer-float-png-old-fashion-root-beer.png', 'A nostalgic treat featuring creamy vanilla ice cream floating in a frosty mug of bubbly root beer.'),
    ('French Fries', 1.99, 'Side', 'fries,salt',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.pngkey.com/png/full/8-86527_french-fries-french-fries-png.png', 'Crispy golden fries served hot and seasoned to perfection, the perfect accompaniment to any meal.'),
    ('Chicken Tenders', 4.99, 'Side', 'crispy chicken tenders,fries,spicy ranch sauce',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.pngkey.com/png/full/263-2639280_breaded-chicken-tenders-chicken-tender-png.png', 'Crispy breaded chicken tenders served with your choice of dipping sauce, perfect for snacking or as a main course.'),
    ('Water', 1.79, 'Beverage', 'water,cups,ice',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://pngimg.com/uploads/water_bottle/water_bottle_PNG10169.png', 'Refresh yourself with a crisp, cool glass of water.'),
    ('Pepsi', 1.99, 'Beverage', 'soda flavors,cups,ice',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://purepng.com/public/uploads/large/purepng.com-pepsifood-drink-beverage-941524621605hb2v7.png', 'Enjoy the classic cola taste of Pepsi, served chilled and fizzy.'),
    ('Corn Dog', 4.99, 'Snack', 'hot dog sausages,corn dog batter,ketchup,mustard',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.pngkey.com/png/full/42-425236_corn-dog.png', 'A classic fairground treat featuring a savory hot dog sausage dipped in cornmeal batter, deep-fried to golden perfection on a stick.'),
    ('Hot Dog', 4.99, 'Snack', 'hot dog sausages,buns,ketchup,mustard',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.pngall.com/wp-content/uploads/2016/04/Hot-Dog-Transparent.png', 'A beloved classic featuring a juicy grilled hot dog sausage nestled in a soft bun, topped with your choice of condiments.'),
    ('Kettle Chips', 0.99, 'Snack', 'kettle chips',  TIMESTAMP '2022-02-01 00:56:04', NULL, 'https://www.pngkey.com/png/full/389-3899499_kettle-cooked-original-potato-chips-lays-kettle-cooked.png', 'Crunchy kettle-cooked potato chips, seasoned with just the right amount of salt for a satisfying snack.');
